name: shtest
version: 0.0.0

dependencies:
- base >= 4.7 && < 5
- aeson
- pcre-light
- serverless-haskell

library:
  source-dirs: src

executables:
  mylambda:
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - lens
      - text
      - unordered-containers
