service: NAME

provider:
  name: aws
  runtime: haskell

functions:
  main:
    handler: Lib.handler

  apigw:
    handler: Lib.apiGatewayHello
    events:
      - http:
          path: hello/{name}
          method: get

  jsfunc:
    runtime: nodejs8.10
    handler: jsfunc/handler.main

plugins:
- serverless-haskell
- serverless-offline

custom:
  haskell:
    # environment variables appear as strings. Index that string into a
    # dictionary with actual boolean values to get the boolean back
    docker: ${self:custom.boolean.${env:FORCE_DOCKER, "DOCKER_DEFAULT"}}
  boolean:
    true: true
    false: false
